apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "steve-server.fullname" . }}-cluster-admin
  labels:
    {{- include "steve-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "steve-server.fullname" . }}
    namespace: {{ .Release.Namespace }}
