apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "steve-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steve-server.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steve-server.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "steve-server.fullname" . }}
  labels:
    {{- include "steve-server.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
