apiVersion: v1
kind: Service
metadata:
  name: {{ include "steve-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steve-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "steve-server.selectorLabels" . | nindent 4 }}
