image:
  repository: "nwmac/standalone"
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpsPort: 9443
  httpPort: 9080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
